#Example configuration options that can be placed in your main SiriProxy config.yml
##########################
#NOTICE: Modifying these options in this file has no effect. You must put them in SiriProxy's config.yml!
##########################

     - name: 'AdultJokes'
       path: './plugins/siriproxy-adultjokes'
       host: 'http://192.168.69.95' #IP address of web server hosting your custom pictures
  
